spring.application.name=ECommerce
server.port=8081
spring.profiles.active=local
# Database
#spring.datasource.url=jdbc:postgresql://localhost:5432/ecommerce
#spring.datasource.username=postgres
#spring.datasource.password=1234
#spring.datasource.driver-class-name=org.postgresql.Driver

#Second Database
spring.datasource.url=jdbc:mariadb://localhost:3306/springai
spring.datasource.username=root
spring.datasource.password=root1234
spring.datasource.driver-class-name=org.mariadb.jdbc.Driver
spring.ai.vectorstore.mariadb.initialize-schema=true
spring.ai.vectorstore.mariadb.distance-type=COSINE
spring.ai.vectorstore.mariadb.dimensions=1024


# JPA / Hibernate
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MariaDBDialect
spring.jpa.hibernate.ddl-auto=update

# Security Configuration
jwt.secret=${JWT_SECRET}

# Google OAuth2
spring.security.oauth2.client.registration.google.client-id=${GOOGLE_CLIENT_ID}
spring.security.oauth2.client.registration.google.client-secret=${GOOGLE_CLIENT_SECRET}
spring.security.oauth2.client.registration.google.scope=openid,profile,email
spring.security.oauth2.client.registration.google.redirect-uri=http://localhost:8081/login/oauth2/code/google
spring.security.oauth2.client.registration.google.authorization-grant-type=authorization_code
spring.security.oauth2.client.provider.google.issuer-uri=https://accounts.google.com
spring.security.oauth2.client.provider.google.user-name-attribute=sub

# Frontend Redirect
app.oauth2.redirect-uri=http://localhost:8081/oauth-success?accessToken=

stripe.api.key=${STRIPE_API_KEY}

# File Upload
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB

# Server Tuning
server.tomcat.threads.max=400
server.tomcat.accept-count=150

logging.file.path=C:\\E_Commerce\\ECommerce


# Base URL for the local Ollama API
spring.ai.ollama.base-url=http://localhost:11434
spring.ai.ollama.chat.options.model=mistral
#tinyllama
# llama3.1:8b
spring.ai.ollama.chat.options.temperature=0.2
spring.ai.ollama.init.pull-model-strategy=never

#advisor logging
logging.level.org.springframework.ai.chat.client.advisor=DEBUG

# Disable automatic JDBC Chat Memory schema initialization
spring.ai.chat.memory.repository.jdbc.initialize-schema=never


# To store memory of prevous chat
#spring.ai.chat.memory.repository.jdbc.initialize-schema=ALWAYS

##Base URL for Open AI
#spring.ai.openai.api-key=
#spring.ai.openai.chat.options.model=gpt-4.1
## llama3.1:8b
#spring.ai.openai.chat.options.temperature=0.7


# to diaable auto selection of client due to multiple model
#spring.ai.chat.client.enabled=false